name:          Code Guide by Lightningkite
description:   Standards for developing flexible, durable, and sustainable code.
url:           http://lightningkite.github.io
baseurl:       /style

markdown:      rdiscount
permalink:     pretty
highlighter:   pygments
